# Generated by Django 6.1 on 2026-08-13 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='control',
            name='mascota',
        ),
        migrations.AddField(
            model_name='control',
            name='costo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='datos_ing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='edad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='procedimiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='veterinario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='peso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nchip', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('meses', models.IntegerField(blank=True, null=True)),
                ('peso', models.CharField(blank=True, max_length=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('estd_rep', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ins', models.DateTimeField(blank=True, null=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.dueno')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.paciente'),
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacunas', models.CharField(blank=True, max_length=300, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='General.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='id_vet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='General.veterinario'),
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
