# Generated by Django 6.1 on 2026-08-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_veterinario_remove_control_mascota_control_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
