# Generated by Django 6.1 on 2026-08-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_paciente_genero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Control',
            new_name='Agenda',
        ),
        migrations.RenameModel(
            old_name='Vacunas',
            new_name='VacunasPaciente',
        ),
    ]
