# Generated by Django 6.1 on 2026-08-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_rename_control_agenda_rename_vacunas_vacunaspaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('precio', models.PositiveIntegerField(blank=True, null=True)),
                ('descuento', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
