# Generated by Django 6.1 on 2026-08-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0005_insumo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacunaspaciente',
            old_name='vacunas',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='vacunaspaciente',
            name='vacuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='General.insumo'),
        ),
    ]
