# Generated by Django 6.1 on 2026-08-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_rename_vacunas_vacunaspaciente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunaspaciente',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
