# Generated by Django 6.1 on 2026-08-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0007_vacunaspaciente_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='temperatura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
