# Generated by Django 6.1 on 2026-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0008_agenda_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='meses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
