# Generated by Django 6.1 on 2026-08-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0009_agenda_meses_alter_agenda_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='datos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='paricion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
