# Generated by Django 6.1 on 2026-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0010_paciente_datos_paciente_paricion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='id_vet',
        ),
        migrations.DeleteModel(
            name='Veterinario',
        ),
    ]
