# Generated by Django 6.1 on 2026-08-14 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0011_bodega_personal_remove_agenda_id_vet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='id_vet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='General.personal'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='encargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='General.bodega'),
        ),
    ]
