# Generated by Django 6.1 on 2026-08-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0012_agenda_id_vet_bodega_encargado_bodega_ubicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='profesion',
            new_name='cargo',
        ),
    ]
