# Generated by Django 6.0.5 on 2026-08-17 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0013_rename_profesion_personal_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Atención Médica', 'Atención Médica'), ('Hospital', 'Hospital'), ('Quirúrgica', 'Quirúrgica'), ('Terreno', 'Terreno'), ('Tratamiento', 'Tratamiento')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CirugiasPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='General.paciente')),
                ('procedimiento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='General.procedimiento')),
            ],
        ),
    ]
