# Generated by Django 6.1 on 2026-08-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0015_especie_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
