# Generated by Django 6.1 on 2026-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0016_alter_agenda_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Atención Médica', 'Atención Médica'), ('Hospital', 'Hospital'), ('Quirúrgica', 'Quirúrgica'), ('Terreno', 'Terreno'), ('Tratamiento', 'Tratamiento')], max_length=50, null=True),
        ),
    ]
