# Generated by Django 6.1 on 2026-08-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0017_alter_agenda_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='cancelado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
