# Generated by Django 6.1 on 2026-08-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0018_agenda_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='cancelado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
