# Generated by Django 6.1 on 2026-08-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0019_agenda_origen_alter_agenda_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='origen',
            field=models.CharField(blank=True, default='Agenda', max_length=100, null=True),
        ),
    ]
